### ISSUE TITLE
Relay Issue

### ISSUE THREAD

**Issue by Feneel518** [sinricpro/esp8266-esp32-sdk#165]
When i upload the code to NODEMCU the relay is already turned on and when i say turn on lights to alexa it turns off the relay. Please help me with that.
Thank You.

**Comment by sivar2311** [comment]
- What code are you uploading?
- What type of relay are you using and finally
- How is the wiring?

**Comment by Feneel518** [comment]
Actually i got the answer, just had to change the status.

**Comment by Feneel518** [comment]
btw @sivar2311 can u help me with combining certain relays to group so that i can turn on or off with a single command

**Comment by sivar2311** [comment]
> Actually i got the answer, just had to change the status.

... or the wiring... ;)

> can u help me with combining certain relays to group so that i can turn on or off with a single command

What about using Alexa routines / scenes ?

Maybe i got your question wrong. If this is so, please provide detailed information! 
- I don't know anything about your device
- I dont't know anything about your code
- I don't know anything about the expected behavior
- No... I do not own a fortune teller crystal ball ;)
