### ISSUE TITLE
Sinricpro with ESPAsyncWebServer without SDK library

### ISSUE THREAD

**Issue by smartswitchsio** [sinricpro/esp8266-esp32-sdk#176]
How to use sinricpro with ESPAsyncWebServer without SDK library

**Comment by sivar2311** [comment]
To use SinricPro without this library, you would have to implement the whole protocol yourself, including the calculation of the digital signature.

See the[ sample messages](https://github.com/sinricpro/sample_messages) for this.

**Comment by sivar2311** [comment]
You are switching the topics between AsyncWeb**Socket** and Async**WebServer**

Question: Is your issue about SERVER or SOCKET ?

Please provide detailed information.

**Comment by smartswitchsio** [comment]
Kindly provide details to use with AsyncWebSocket

**Comment by sivar2311** [comment]
If you have an issue with WebSockets
1. Share your code (create a git repository or use gist.github.com) so I will be able to reproduce the error you have
2. Provide detailed informations (debug logs etc etc.)

**Comment by smartswitchsio** [comment]
Kindly find the link for my git repository link  https://github.com/smartswitchsio/testing

Problem
1. Web page not loading if i use with Sinricpro, with out Sinricpro its working fine

**Comment by sivar2311** [comment]
The code is much too large for an error analysis. Just from a source code I can't see the function the device should do.

Please provide me with a simple (as small as possible and easy to understand) example project to perform a bug analysis. Reduce your sketch to a minimum which shows the error and remove all other functions.

Then tell me what the function of the sketch should be and give me an instruction when / how the error happens and how I can trigger this.

**Comment by smartswitchsio** [comment]
please find the git repository link https://github.com/smartswitchsio/test1
If i removed this library working fine #include <AsyncElegantOTA.h>
Kindly check with this library and guide me how to use with this .

**Comment by sivar2311** [comment]
Is the sketch from above the bare minimum to reproduce the problem? 
It still looks very complex and includes functions that do not help troubleshooting.

You still haven't told me what the sketch is about. I do not know the functionality!

I cannot check these libraries (because I am not the author of these libraries) nor can I tell you how to use them. Please contact the authors of the respective libraries for this.

**Comment by smartswitchsio** [comment]
I added with minimum only , this sketch is used to control three relays from web page

**Comment by sivar2311** [comment]
"added with minimum" means you removed code and files, or did you create a new repository?

Question: Why do you use `ICACHE_FLASH_ATTR` so often?? Most of the functions doesn't look like ISR's to me... so why do you do this?

**Comment by smartswitchsio** [comment]
Code removed and created new repository,
 i have basic knowledge only.

**Comment by sivar2311** [comment]
The code is way to much complex only for a simple web control of 3 relays.
You should keep this simpler. 
ESPAsyncCould be used as webserver without any issues.

What does the AsyncWebSocket does? 
I can't see the function from the code.

And still the question about all those `ICACHE_FLASH_ATTR` !?

**Comment by smartswitchsio** [comment]
I gave you simplified sketch but we have more functions

**Comment by sivar2311** [comment]
Please answer all my questions

**Comment by smartswitchsio** [comment]
hi bro, i want to control 3 relays from web page, sinricpro and traditional switch with store custom configuration in fs (Like ssid, password, mqtt server details and if have any ), that s all. this is the think i am trying to do

**Comment by sivar2311** [comment]
Hi "Bro".

I think for this I have already given you a few days ago a [detailed example](https://github.com/sinricpro/esp8266-esp32-sdk/issues/166#issuecomment-808856420)! 

If it's really just about a stupid web interface, why don't you take my suggestion? After all, I've already done all the work for you.

Why any other library doesn't work for you, I don't know. And I have neither the time nor the desire to analyze that. Ask the developer of the not working library, what the issue is.
