### ISSUE TITLE
Slow feedback link from SinricPro to Alexa?

### ISSUE THREAD

**Issue by vanginger** [sinricpro/esp8266-esp32-sdk#190]
About a year ago, I used the Garagedoor project on here.  I added my reed switches and it worked fantastically well :)

I am not sure when, but sometime in the last few months, Alexa has stopped recognising the door state just after it has been opened or closed.
If I use Alexa or the Alexa app to close the door, it will close, then say Sorry, there is no response from Garage Door. (or something similar)
If I use the SinricPro app to close and open it, it change state the second the door actually closes or opens and is ready to go again.
Alexa does eventually recognise the state of the door, I am not sure how long after though, but it's definitely not within a few seconds like it used to be.
Any ideas? Has anytihng changed?

**Comment by kakopappa** [comment]
Usually, Alexa says "there is no response from the device" when the device fails to respond or did not respond within 20 seconds for lock device type / and 7 seconds (other than lock) to Alexa. These values are defined by Alexa, not us! 

Maybe your code fails to respond within the appropriate time-out. If the problem persists, try the Lock device type instead of Garage Door.

**Comment by vanginger** [comment]
Ah, that timing makes sense.
Thing is, it did work fine up until the new year, give or take a couple of months. I havent touched the ESP device at all, so no code has changed.
Although it does control the Garage Door, it is a Lock device type, it's the code that @sivar2311 wrote.
