### ISSUE TITLE
Version 2.9.5

### ISSUE THREAD

**Issue by sim404** [sinricpro/esp8266-esp32-sdk#197]
Many thanks for the new Release. A request please. Could you give some detail for:
“Improved error message when a callback is not implemented”
What is the improvement and how to make use of it please.
Regards, sim404

**Comment by kakopappa** [comment]
Sometimes you may see this error if the callback is not handled in the code.

![image](https://user-images.githubusercontent.com/7474406/124151759-17543200-dabd-11eb-93e6-c79f23478bb1.png)

This message is not really helpful since it doesn't tell you which callback is missing. Changed the error message to say which call back is missing.

**Comment by sim404** [comment]
Thanks. Understood.

**Comment by sim404** [comment]
And closing the issue now.
