### ISSUE TITLE
esp01 not responding while connected to hardware

### ISSUE THREAD

**Issue by abhinavkala** [sinricpro/esp8266-esp32-sdk#248]
i put my arduino code from the ide to the esp01 successfully with the help of an fdti adaptor and when i removed the gpi00 from the ground and inserted the adaptor again ,the esp01 connected to the wifi and responded to the alexa commands .But when i removed the esp01 and connected to the hardware the esp01 isn't responding to the commands. The esp01 is powered up properly but aint connecting with the wifi while on hardware .the baud rate is also 115200 as per the need

**Comment by kakopappa** [comment]
Have you checked whether ESP01 going to download mode ?

**Comment by abhinavkala** [comment]
u mean programming mode.?

**Comment by sivar2311** [comment]
If it is not working when the ESP-01 is connected to your hardware, please note the following:

GPIO0: boot failure if pulled LOW
GPIO1: pin is high at BOOT, boot failure if pulled LOW
GPIO2: pin is high on BOOT, boot failure if pulled LOW
GPIO3: pin is high at BOOT

You will find more informations [here](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)

It seems your issue is not related to the SinricPro SDK, but to your hardware.

**Comment by abhinavkala** [comment]
> If it is not working when the ESP-01 is connected to your hardware, please note the following:
> 
> GPIO0: boot failure if pulled LOW GPIO1: pin is high at BOOT, boot failure if pulled LOW GPIO2: pin is high on BOOT, boot failure if pulled LOW GPIO3: pin is high at BOOT
> 
> You will find more informations [here](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)
> 
> It seems your issue is not related to the SinricPro SDK, but to your hardware.

**Comment by abhinavkala** [comment]
ye

> If it is not working when the ESP-01 is connected to your hardware, please note the following:
> 
> GPIO0: boot failure if pulled LOW GPIO1: pin is high at BOOT, boot failure if pulled LOW GPIO2: pin is high on BOOT, boot failure if pulled LOW GPIO3: pin is high at BOOT
> 
> You will find more informations [here](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)
> 
> It seems your issue is not related to the SinricPro SDK, but to your hardware.

i did this …still not connecting to wifi while on hardware …the esp01 is powered up and the red led is on ,but not connecting to wifi🥲

**Comment by sivar2311** [comment]
If I understand correctly, the ESP-01 runs without errors when it is not connected to your hardware. 
As soon as the ESP-01 is connected to your hardware, the error occurs.
This is a basic problem, caused by your hardware (which I don't know).
Therefore, I can only share with you the advice regarding the GPIOs from my previous post.

Have you tried another (non SinricPro) sketch with WiFi functionality when the ESP-01 is connected to your hardware?

**Comment by abhinavkala** [comment]
> If I understand correctly, the ESP-01 runs without errors when it is not connected to your hardware. As soon as the ESP-01 is connected to your hardware, the error occurs. This is a basic problem, caused by your hardware (which I don't know). Therefore, I can only share with you the advice regarding the GPIOs from my previous post.
> 
> Have you tried another (non SinricPro) sketch with WiFi functionality when the ESP-01 is connected to your hardware?

no, ill just try that and update here

**Comment by durobhash** [comment]
Hi,

I am facing similar issue with different ESP boards (01, 12, Dev module, D-1). After successful compilation and upload, It’s stuck at the WiFi connect stage and crashing. I tried with WiFi manager to see if the issue is with broken package, also reinstalled package, but no result. What do you think going wrong here?

**Comment by sivar2311** [comment]
I think it's the same with WiFiManager as with SinricPro: If the underlying WiFi doesnt work no dependent WiFi library will work.
If your ESP-01 WiFi is working when it is running standalone, and not working when the ESP-01 is connected to your hardware -> The issue is with your hardware.

**Comment by sivar2311** [comment]
@durobhash Please open a new issue and post your sketch for analysis, i will have take a look.
