### ISSUE TITLE
Fetch thermostat temperature from sinric server to esp8266 on reboot

### ISSUE THREAD

**Issue by amanjn92** [sinricpro/esp8266-esp32-sdk#266]
Hi

I am trying to make a thermostat which regulates my AC (using IR LED acting as remote) and a fan (using relay) depending upon room temperature (using DHT11). I have been able to put everything together but am facing 1 small issue. **_I don't know how to fetch the thermostat temperature from the server when the device restarts._**

In my code, when somebody changes the thermostat temperature, that temperature is set as low temperature (temp at which AC shuts down and Fan switches on).

bool onTargetTemperature(const String &deviceId, float &temperature) {
  Serial.printf("Thermostat %s set temperature to %f\r\n", deviceId.c_str(), temperature);
  
if (controlstatus==true){
  lowtemp = temperature;
  hightemp = lowtemp+2;
}

This happens only when somebody changes the thermostat temp using Google Home. **_How do I make this happen everytime the device restarts or periodically say once every hour?_**

**Comment by sivar2311** [comment]
Hello @amanjn92 !

The desired temperature is transmitted to your device in the onTargetTemperature callback. 
You should save the temperature in a variable so that your Sketch can access it at any time. 

To "fetch" this value from the server when your device is restarted, call the function `SinricPro.restoreDeviceStates(true);` before calling `SinricPro.begin(...)`. 

When your device is restarted, the last value known to the server is then transferred to your device (using `onTargetTemperature`). So you don't need to implement anything else.

Please see the [documentation for restoreDeviceStates](https://sinricpro.github.io/esp8266-esp32-sdk/class_sinric_pro_class.html#a27a9bb7f1e8bde0f39398649493b6f93)

**Comment by amanjn92** [comment]
Hi Sivar2311

I have embedded this in my code already and this is able to fetch everything from the server except for the thermostat temperature reading. See my code below:

**onTargetTemperature Part:**

float lowtemp;
float hightemp;

bool onTargetTemperature(const String &deviceId, float &temperature) {
  Serial.printf("Thermostat %s set temperature to %f\r\n", deviceId.c_str(), temperature);
  
  lowtemp = temperature;
  hightemp = lowtemp+2;
}

**Setup Part:**

void setupSinricPro() {
  
  SinricProSwitch& mySwitch1 = SinricPro[SWITCH_ID1];          // LIGHT
  mySwitch1.onPowerState(onPowerState1);

  SinricProSwitch& mySwitch2 = SinricPro[SWITCH_ID2];         // FAN
  mySwitch2.onPowerState(onPowerState2);

   SinricProThermostat &myThermostat = SinricPro[THERMOSTAT_ID];    // Control & AC
  myThermostat.onPowerState(onPowerState);
  myThermostat.onThermostatMode(onThermostatMode);
  myThermostat.onTargetTemperature(onTargetTemperature);


  SinricPro.onConnected([](){ Serial.printf("Connected to SinricPro\r\n"); }); 
  SinricPro.onDisconnected([](){ Serial.printf("Disconnected from SinricPro\r\n"); });

  SinricPro.restoreDeviceStates(true); // get latest known deviceState from server (is device turned on?)
    SinricPro.begin(APP_KEY, APP_SECRET);
}

Please let me know what am I doing wrong.
