### ISSUE TITLE
Alexa doesnt seem to think the TV_example is a video device

### ISSUE THREAD

**Issue by sim404** [sinricpro/esp8266-esp32-sdk#300]
Hi, I've been using the TV example code successfully for sometime, but mainly only to turn it on/off and volume. Changing channels had worked fine previously but strangely now it  doesn't. 

My device name is 'LG'. When I say "Alexa, LG on/off/mute/volume+/-" etc, they all work fine. But when I say e.g "Alexa, change channel to 233 on LG", it doesn't work now but did previously. Instead Alexa responds "I couldn't find a device or group named LG in (name) profile". So I created a group using the Alexa APP and put 'LG' into it. No change, still not working. I hadn't compiled my TV code for a year or so figured that was the reason. No it wasn't. I put my credentials in the stock TV_example but that hasn't fixed it either. 

Lastly, I tried using the SinricPro APP to control the 'LG'. It does mute, volume, on/off etc no problem. But when you try channel +/- it actually does do it immediately (as seen on the serial port) but there's no response back on the APP, until approx 8secs later the sinricP APP reports 'Device did not respond within the timeout period (8 seconds)' .

Could it be that for some reason AWS doesn't see SinricPro TV as a video skill anymore?? Views please.

Regards, Steve
PS: thanks for fixing my doorbell mystery recently

**Comment by kakopappa** [comment]
Hi @sim404 

Sinric Pro app: Channel +/- not working correctly because of a bug (response from ESP is not handled). I will fix this in the next release. 

Portal: Missing the Channel +/- . I will add this in the next release.

![image](https://user-images.githubusercontent.com/7474406/203103911-b4960c62-5a8f-4490-846a-d73b8b6948e1.png)

About Alexa, I did a quick test and seems to work for me. 

![image](https://user-images.githubusercontent.com/7474406/203103829-b714b7f1-7bfc-4dc7-8e9b-20c210e09db3.png)


We have not made any changes to Alexa's skill recently as well. I do like to recommend you rename LG to TV and trying again

**Comment by sim404** [comment]
ok, understood. So the sinricP APP issue is not connected to my Alexa issue. That narrows it down so thanks for that. I'll try the rename but if not and having given it further thought I think the Alexa issue with sinricP 'LG' may have started sometime back when I installed a FireTV for use in another room (same wifi) and Alexa now getting confused about that. Anyway I'll investigate further. Thanks, Regards, Steve
