### ISSUE TITLE
Enable and Disable A4988 stepper driver with ESP8266 digital pin

### ISSUE THREAD

**Issue by Tharos88** [sinricpro/esp8266-esp32-sdk#386]
Hi!

I am using a stepper motor and an A4988 driver for the movement of the blind. The problem is that the motor gets too hot and I want to add an option in the source code so that when the motor finishes rotating, send a pin to High to turn off the driver and when it is activated again, send the pin to Low to activate A4988. Where in the code can I place this option?

It is worth noting that the driver is well configured and using complete steps.

Thank you!

**Comment by kakopappa** [comment]
Since you haven't posted your code only you would know. 

Here's a general guideline on how to achieve this:

1. **Define the Pin**: Choose a pin that will control the enable/disable signal for your A4988 driver. For this example, let's assume you're using GPIO pin 8.

2. **Initialize the Pin**: Set the chosen pin as an output in the `setup()` function of your Arduino (or the equivalent initialization function in other platforms).

3. **Control the Pin**: Place the logic to control this pin in your code where you start and stop the motor.

### Example in Arduino

Assuming this is an Arduino sketch, here’s how you can incorporate it:

#### Define the Pin in the Declarations:
```cpp
#define DRIVER_ENABLE_PIN 8  // Pin 8 to control the driver enable
```

#### Initialize the Pin in the `setup()` Function:
```cpp
void setup() {
  pinMode(DRIVER_ENABLE_PIN, OUTPUT);
  digitalWrite(DRIVER_ENABLE_PIN, HIGH);  // Start with the driver disabled

  // Other initialization code
}
```

#### Modify the Code to Control the Driver:
Let's assume you have functions like `startMotor()` and `stopMotor()` where the motor is activated and deactivated.

```cpp
void startMotor() {
    // Enable the driver
    digitalWrite(DRIVER_ENABLE_PIN, LOW);

    // Add your code to start motor movement
    // Example:
    // stepper.moveTo(targetPosition);  // or however you start your motor
}

void stopMotor() {
    // Add your code to stop motor movement
    // Example:
    // stepper.stop();  // or however you stop your motor

    // Disable the driver
    digitalWrite(DRIVER_ENABLE_PIN, HIGH);
}
```

#### Example Usage
Here’s how you might call these functions in your main loop or other parts of your code:

```cpp
void loop() {
    // Example condition to start the motor
    if (conditionToStartMotor) {
        startMotor();
    }

    // Example condition to stop the motor
    if (conditionToStopMotor) {
        stopMotor();
    }

    // Add other code for your loop
}
```

### Summary
