### ISSUE TITLE
device_id value ger from flash not working instance problem

### ISSUE THREAD

**Issue by turandalkilic** [sinricpro/esp8266-esp32-sdk#403]
Hi

```
#define DEVICE_ID "65f043ab46a89b75c2738965"
///////////////////////////////////////
DenemeEv &denemeEv = SinricPro[DEVICE_ID];
```

This sample is working normaly 

---------------------------------------
// but 
// if i want to device id value from preferences flah memory 

```
#define DEVICE_ID deviceId3
DenemeEv &denemeEv = SinricPro[deviceId3];

void setup(){ 
String deviceId3 = prefDeviceID.getString("st_deviceId3").c_str();
Serial.println(deviceId3); //65f043ab46a89b75c2738965 getting normal value
}

DenemeEv &denemeEv = SinricPro[DEVICE_ID]; // problem is here 
// if i write static value working but get from storage not working
```

not working 
------------------------------------------------
how can i get deviceid value from storage
thanks

**Comment by kakopappa** [comment]
do you need `.c_str()` ? `String deviceId3 = prefDeviceID.getString("st_deviceId3");` should be sufficent.

**Comment by sivar2311** [comment]
If you want to store and load the device id in flash memory, you can't do that on a global scope's device reference variable, because the preference library is not initialized and available at this point in time. Which means, the deviceId is also not available yet.

In this case you cannot use global device references.

Fortunately, you can obtain the device reference at any point in your code - see [How to retreive a device for sending an event](https://github.com/sinricpro/esp8266-esp32-sdk/tree/master?tab=readme-ov-file#how-to-retrieve-a-device-for-sending-an-event)

- Use global scoped deviceId variables

- Load the deviceId(s) in `setup()`

- In every function you need to access the device, create local device reference variable by calling `MyDeviceType& myDevice = SinricPro[<global_device_id_variable_here>];`

**Comment by turandalkilic** [comment]
Hi 
I tried something but it isnt what I want to. 
c_str() not working. There isnt any error. 
Compailing is OK. 
connected String Pro ok. 
but in sinricpro web page i cant send a message.   

MyDeviceType& myDevice = SinricPro[here_is_static_or_ global_ devices_value_required];

I want to use different esp32 devices and only one program. 
But  every devices wants different programs so only change deviceID, 
(app_key, _ appScret same value)

the deviceId is also not available at this time ---> then not getting another place deviceId value (silvar2311 i aggre with you)
MyDeviceType& myDevice = SinricPro[everything_is_same_only_here_different] 
Thanks

**Comment by sivar2311** [comment]
Hi @turandalkilic !

Unfortunately, I did not understand your reply. 
Were you able to solve the problem or do you need further help?

**Comment by turandalkilic** [comment]
Hi 
I did it.

I moved this line  
MyDeviceType& myDevice = SinricPro[deviceid] /// Here is not getting preferences ( glabal area )

to

void setupSinricPro()
{
 String deviceid = oku_deviceId3.c_str(); // and I get preferences value
 MyDeviceType& myDevice = SinricPro[deviceid] ///  I puted here 
}

///////////////////////

void setup()
{
	setupSinricPro();	// setup block has preferences data
}
	
void loop()
{
setupSinricPro();
 ///////////////////
  SinricPro.handle(); /// 
}

thanks

**Comment by sivar2311** [comment]
It looks like this issue can be closed.
If you have still questions about this topic, feel free to reopen the issue.
