### ISSUE TITLE
which pins are used

### ISSUE THREAD

**Issue by luconezena** [sinricpro/esp8266-esp32-sdk#46]
Hello everyone from Italy, questions: which pins are used? example,  DimSwitch pin used? where can I change the pin layout.
Thanks and sorry my english/google

**Comment by sivar2311** [comment]
Hi! Because this are **examples** to show **how to interact with SinricPro**, 
This are not examples about how to turn on / off an LED, etc.

SinricPro is highly flexible. You can control whatever circuit you want to build. But pin definitions will depend on your circuit, not on how to communicate with SinricPro server.

Please keep in mind: this are examples, no finally implementations or projects.

**Comment by luconezena** [comment]
thanks, you were very kind
